---
- name: Set setting variables
  ansible.builtin.set_fact:
    setting_name: "{{ backup_setting.key }}"
    setting: "{{ backup_setting.value }}"
- name: Create backup data directory
  ansible.builtin.file:
    path: "{{ backup_data_dir }}/{{ setting_name }}"
    state: directory
    owner: "{{ setting.user }}"
    mode: "0750"
- name: Create/update rclone setting
  when: setting.rclone is defined
  become: true
  become_user: "{{ setting.user }}"
  block:
    - name: Create rclone config directory
      ansible.builtin.file:
        path: ~/.config/rclone
        state: directory
        mode: "0755"
- name: Generate backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: "{{ backup_script_dir }}/{{ setting_name }}"
    owner: "{{ setting.user }}"
    mode: "0700"
  register: template_result
- name: Set backup cron jobs
  ansible.builtin.cron:
    user: "{{ setting.user }}"
    name: "role:backup/setting:{{ setting_name }}"
    job: "{{ template_result.dest }}"
    month: "{{ setting.cron.month | default(omit) }}"
    day: "{{ setting.cron.day | default(omit) }}"
    hour: "{{ setting.cron.hour | default(omit) }}"
    minute: "{{ setting.cron.minute | default(omit) }}"
    weekday: "{{ setting.cron.weekday | default(omit) }}"
    disabled: "{{ setting.cron.disabled | default(false) }}"
