# code: language=ansible
---
- name: Create backup directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ backup_base_dir }}"
    - "{{ backup_script_dir }}"
    - "{{ backup_data_dir }}"
    - "{{ backup_repo_dir }}"


- name: Setup backup setting
  ansible.builtin.debug:
    var: backup_settings
  # ansible.builtin.include_tasks:
  #   file: setting/backup.yml
  # loop: "{{ backup_settings | dict2items(key_name='name', value_name='setting') }}"
  # loop_control:
  #   loop_var: backup_setting
  #   label: "{{ backup_setting.name }}"
