---
- name: Install restic
  ansible.builtin.apt:
    name: restic
- name: Execute restic self update
  ansible.builtin.command:
    cmd: restic self-update
    removes: /usr/bin/restic
  changed_when: false
