---
backup_settings:
  ## バックアップ処理の指定：有り、バックアップデータの世代管理：無し
  test_command_only:
    user: command_only
    cron:
      hour: 1
      minute: 23
    command: rclone test makefile 1234 ${BACKUP_DATA_DIR}/test.txt
  ## バックアップ処理の指定：無し、バックアップデータの世代管理：有り
  test_restic_only:
    user: restic_only
    cron:
      hour: 1
      minute: 23
    restic:
      target: /home/restic_only/dummy
      repo_password: test_restic_only_p@55w0rd
  ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
  test_restic_default:
    user: restic_default
    cron:
      hour: 1
      minute: 23
    command: rclone test makefile 1234 ${BACKUP_DATA_DIR}/test.txt
    restic:
      repo_password: test_restic_default_p@55w0rd
  ## バックアップ処理の指定：無し、バックアップデータの世代管理：有り
  ## 外部ストレージ(rclone経由)を利用した世代管理の指定
  test_restic_only_with_rclone:
    user: restic_only_with_rclone
    cron:
      hour: 1
      minute: 23
    restic:
      repo_type: rclone
      repo: cloudflare_r2:test/restic_only_with_rclone
      repo_password: test_restic_only_with_rclone_p@55w0rd
    rclone:
      cloudflare_r2:
        type: s3
        provider: Cloudflare
        access_key_id: "{{ lookup('env', 'CLOUDFLARE_R2_ACCESS_KEY_ID') }}"
        secret_access_key: "{{ lookup('env', 'CLOUDFLARE_R2_SECRET_ACCESS_KEY') }}"
        region: auto
        bucket_acl: private
        endpoint: "{{ lookup('env', 'CLOUDFLARE_R2_ENDPOINT') }}"
  ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
  ## keepパラメーターの指定による世代数の指定有り
  test_restic_forget_keep_param:
    user: restic_forget_keep_param
    cron:
      hour: 1
      minute: 23
    command: rclone test makefile 1234 ${BACKUP_DATA_DIR}/test.txt
    restic:
      repo_password: test_restic_forget_keep_param_p@55w0rd
      forget_keep_type: hourly
      forget_keep_value: 6
  ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
  ## バックアップ終了後に`restic forget`を実行しない
  test_restic_no_forget:
    user: restic_no_forget
    cron:
      hour: 1
      minute: 23
    command: rclone test makefile 1234 ${BACKUP_DATA_DIR}/test.txt
    restic:
      repo_password: test_restic_no_forget_p@55w0rd
      forget: false
  ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
  ## 過去3日以内の日次スナップショットと、直近24時間以内の時間毎スナップショットを残してスナップショットをクリーンアップする
  test_restic_other_forget_option:
    user: restic_other_forget_option
    cron:
      minute: 23
    command: rclone test makefile 1234 ${BACKUP_DATA_DIR}/test.txt
    restic:
      repo_password: test_restic_other_forget_option_p@55w0rd
      forget_keep_type: hourly
      forget_keep_value: 24
      forget_other_options:
        - --keep-within-daily 7d
  ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
  ## 外部ストレージ(rclone経由)を利用した世代管理の指定
  test_restic_and_rclone:
    user: restic_and_rclone
    cron:
      hour: 1
      minute: 23
    command: rclone test makefile 1234 ${BACKUP_DATA_DIR}/test.txt
    restic:
      repo_type: rclone
      repo: cloudflare_r2:test/test_restic_and_rclone
      repo_password: test_restic_and_rclone_p@55w0rd
    rclone:
      cloudflare_r2:
        type: s3
        provider: Cloudflare
        access_key_id: "{{ lookup('env', 'CLOUDFLARE_R2_ACCESS_KEY_ID') }}"
        secret_access_key: "{{ lookup('env', 'CLOUDFLARE_R2_SECRET_ACCESS_KEY') }}"
        region: auto
        bucket_acl: private
        endpoint: "{{ lookup('env', 'CLOUDFLARE_R2_ENDPOINT') }}"
  ## 定期実行の指定：なし
  test_no_schdule:
    user: no_schdule
    command: rclone test makefile 1234 ${BACKUP_DATA_DIR}/test.txt
    restic:
      repo_password: test_no_schdule_p@55w0rd
  ## バックアップデータの共有
  ## (同一のグループに所属するアカウントにはデータおよびリポジトリに対する読み取り権限有り)
  test_shared_data_and_repo:
    user: shared_data_and_repo_main
    group: shared_data_and_repo
    cron:
      hour: 1
      minute: 23
    restic:
      repo_password: test_shared_data_and_repo_p@55w0rd
  ## 実例のサンプル
  wordpress:
    user: wordpress
    cron:
      hour: 2
      minute: 22
    environment:
      DB_HOST: localhost
      DB_NAME: wordpress
      DB_USER: wordpress_db_user
      DB_PASSWORD: wordpress_db_password
    command: |
      rclone test makefiles ${BACKUP_DATA_DIR}
      # NOW_DATETIME=$(date +"%Y%m%d_%H%M%S")
      # wp db export ${BACKUP_DATA_DIR}/dump.sql --path /var/www/wordpress
      # tar vcfz ${BACKUP_DATA_DIR}/uploads.tar.gz /var/www/wordpress/wp-content/uploads/*
    restic:
      repo_password: example_wordprss_p@55w0rd
  redmine:
    user: redmine
    cron:
      hour: 3
      minute: 33
    environment:
      DB_HOST: localhost
      DB_NAME: redmine
      DB_USER: redmine_db_user
      DB_PASSWORD: redmine_db_password
    command: |
      rclone test makefiles ${BACKUP_DATA_DIR}
      # NOW_DATETIME=$(date +"%Y%m%d_%H%M%S")
      # mysqldump -u ${DB_USER} -p${DB_PASSWORD} -h ${DB_HOST} --single-transaction ${DB_NAME} >${BACKUP_DATA_DIR}/dump.sql.gz
      # tar vcfz ${BACKUP_DATA_DIR}/files.tar.gz /path/to/redmine/files/*
    restic:
      repo_type: rclone
      repo: cloudflare_r2:test/redmine
      repo_password: example_redmine_p@55w0rd
      forget_keep_type: weekly
      forget_keep_value: 2
    rclone:
      cloudflare_r2:
        type: s3
        provider: Cloudflare
        access_key_id: "{{ lookup('env', 'CLOUDFLARE_R2_ACCESS_KEY_ID') }}"
        secret_access_key: "{{ lookup('env', 'CLOUDFLARE_R2_SECRET_ACCESS_KEY') }}"
        region: auto
        bucket_acl: private
        endpoint: "{{ lookup('env', 'CLOUDFLARE_R2_ENDPOINT') }}"
