---
backup_settings:
  wordpress:
    user: wordpress
    cron:
      hour: 1
      minute: 23
    environment:
      DB_HOST: localhost
      DB_NAME: wordpress
      DB_USER: wordpress_db_user
      DB_PASSWORD: wordpress_db_password
    command: |
      wp db export dump.sql --path /var/www/html
      tar vcfz uploads.tar.gz /var/www/html/wp-content/uploads/
  redmine:
    user: redmine
    cron:
      hour: 2
      minute: 34
    environment:
      DB_HOST: localhost
      DB_NAME: redmine
      DB_USER: redmine_db_user
      DB_PASSWORD: redmine_db_password
    command: |
      mysqldump -u ${DB_USER} -p${DB_PASSWORD} -h ${DB_HOST} --single-transaction ${DB_NAME} | gzip >dump.sql.gz
      tar vcfz files.tar.gz /path/to/redmine/files/
    restic:
      repo_password: very_5tr0ng_p@55w0rd
