# code: language=ansible
---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update cache(apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
      changed_when: false
    - name: Update cache(dnf)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'dnf'
      changed_when: false
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ backup.value.user }}"
      loop: "{{ backup_settings | dict2items }}"
      loop_control:
        loop_var: backup
        label: "{{ backup.value.user }}"
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
