# code: language=ansible
---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update cache(apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'
      changed_when: false
    - name: Update cache(dnf)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'dnf'
      changed_when: false
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ backup.value.user }}"
      loop: "{{ backup_settings | dict2items }}"
      loop_control:
        loop_var: backup
        label: "{{ backup.value.user }}"
    - name: Generate dummy data
      become: true
      become_user: restic_only
      block:
        - name: Create backup target directory
          ansible.builtin.file:
            path: /home/restic_only/dummy
            state: directory
            mode: "0700"
        - name: generate dummy file
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              NOW_DATETIME=$(date +"%Y%m%d_%H%M%S")
              DUMMY_TEXT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 32 | sort | uniq)
              echo "${DUMMY_TEXT}" >/home/restic_only/dummy/dummy_${NOW_DATETIME}.txt
            executable: /bin/bash
          changed_when: false
    - name: Generate dummy data
      become: true
      become_user: restic_only_with_rclone
      block:
        - name: Create backup target directory
          ansible.builtin.file:
            path: /home/restic_only_with_rclone/dummy
            state: directory
            mode: "0700"
        - name: generate dummy file
          ansible.builtin.shell:
            cmd: |
              set -o pipefail
              NOW_DATETIME=$(date +"%Y%m%d_%H%M%S")
              DUMMY_TEXT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 32 | sort | uniq)
              echo "${DUMMY_TEXT}" >/home/restic_only_with_rclone/dummy/dummy_${NOW_DATETIME}.txt
            executable: /bin/bash
          changed_when: false
    - name: Include role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
