# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  vars:
    backup_base_dir: /backup
    backup_script_dir: "{{ backup_base_dir }}/script"
    backup_data_dir: "{{ backup_base_dir }}/data"
    backup_repo_dir: "{{ backup_base_dir }}/repo"
    backup_repo_password_dir: "{{ backup_base_dir }}/password"
  tasks:
    ## パッケージのテスト
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert packages
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['cron'] is defined
          - ansible_facts.packages['rclone'] is defined
          - ansible_facts.packages['restic'] is defined
        fail_msg: "Required backup packages are not installed"
        success_msg: "All required backup packages are installed"
    ## バックアップ処理の指定：有り、バックアップデータの世代管理：無し
    - name: Test command only
      become: true
      become_user: command_only
      block:
        - name: Import testcase test_command_only
          ansible.builtin.import_tasks:
            file: verify/test_command_only.yml
    ## バックアップ処理の指定：無し、バックアップデータの世代管理：有り
    - name: Test restic only
      become: true
      become_user: restic_only
      block:
        - name: Import testcase test_restic_only
          ansible.builtin.import_tasks:
            file: verify/test_restic_only.yml
    ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
    - name: Test command and restic
      become: true
      become_user: command_and_restic
      block:
        - name: Import testcase test_restic_only
          ansible.builtin.import_tasks:
            file: verify/test_command_and_restic.yml
    ## バックアップ処理の指定：無し、バックアップデータの世代管理：有り
    ## 外部ストレージ(rclone経由)を利用した世代管理の指定
    - name: Test restic only with rclone
      become: true
      become_user: restic_only_with_rclone
      block:
        - name: Import testcase test_restic_only_with_rclone
          ansible.builtin.import_tasks:
            file: verify/test_restic_only_with_rclone.yml
    ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
    ## keepパラメーターの指定による世代数の指定有り
    - name: Test restic forget keep param
      become: true
      become_user: restic_forget_keep_param
      block:
        - name: Import testcase test_restic_forget_keep_param
          ansible.builtin.import_tasks:
            file: verify/test_restic_forget_keep_param.yml
    ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
    ## バックアップ終了後に`restic forget`を実行しない
    - name: Test restic no forget
      become: true
      become_user: restic_no_forget
      block:
        - name: Import testcase test_restic_no_forget
          ansible.builtin.import_tasks:
            file: verify/test_restic_no_forget.yml
    ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
    ## 過去3日以内の日次スナップショットと、直近24時間以内の時間毎スナップショットを残してスナップショットをクリーンアップする
    - name: Test restic other forget option
      become: true
      become_user: restic_other_forget_option
      block:
        - name: Import testcase test_restic_other_forget_option
          ansible.builtin.import_tasks:
            file: verify/test_restic_other_forget_option.yml
    ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
    ## 外部ストレージ(rclone経由)を利用した世代管理の指定
    - name: Test restic and rclone
      become: true
      become_user: restic_and_rclone
      block:
        - name: Import testcase test_restic_and_rclone
          ansible.builtin.import_tasks:
            file: verify/test_restic_and_rclone.yml
    ## cronでの定期実行：なし
    - name: Test no schdule
      become: true
      become_user: no_schdule
      block:
        - name: Import testcase test_no_schdule
          ansible.builtin.import_tasks:
            file: verify/test_no_schdule.yml
    ## cronでのバックアップ処理実行時に標準出力の内容を破棄しメールを送信を抑制
    - name: Test cron job suffix
      become: true
      become_user: cron_job_suffix
      block:
        - name: Import testcase test_cron_job_suffix
          ansible.builtin.import_tasks:
            file: verify/test_cron_job_suffix.yml
    ## バックアップデータの共有
    ## (同一のグループに所属するアカウントにはデータおよびリポジトリに対する読み取り権限有り)
    - name: Test shared data and repo
      become: true
      become_user: shared_data_and_repo_main
      block:
        - name: Import testcase test_shared_data_and_repo
          ansible.builtin.import_tasks:
            file: verify/test_shared_data_and_repo.yml
    ## 設定例：WordPress
    - name: Test wordpress
      become: true
      become_user: wordpress
      block:
        - name: Import testcase test_wordpress
          ansible.builtin.import_tasks:
            file: verify/test_wordpress.yml
    ## 設定例：Redmine
    - name: Test redmine
      become: true
      become_user: redmine
      block:
        - name: Import testcase test_redmine
          ansible.builtin.import_tasks:
            file: verify/test_redmine.yml
