# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  vars:
    backup_base_dir: /backup
    backup_script_dir: "{{ backup_base_dir }}/script"
    backup_data_dir: "{{ backup_base_dir }}/data"
    backup_repo_dir: "{{ backup_base_dir }}/repo"
  tasks:
    ## テストの前処理
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
      become: true
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    - name: Assert packages
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['rclone'] is defined
          - ansible_facts.packages['restic'] is defined
    - name: Test command undefined
      become: true
      become_user: command_undefined
      block:
        - name: Check backup script
          ansible.builtin.stat:
            path: "{{ backup_script_dir }}/test_command_undefined"
          register: backup_script_result
        - name: Assert backup script
          ansible.builtin.assert:
            that:
              - backup_script_result.stat.exists
              - backup_script_result.stat.isreg
              - backup_script_result.stat.pw_name == 'command_undefined'
              - backup_script_result.stat.executable
        - name: Check backup data directory
          ansible.builtin.stat:
            path: "{{ backup_data_dir }}/test_command_undefined"
          register: backup_data_dir_result
        - name: Assert backup dir
          ansible.builtin.assert:
            that:
              - backup_data_dir_result.stat.exists
              - backup_data_dir_result.stat.isdir
              - backup_data_dir_result.stat.writeable
              - backup_data_dir_result.stat.pw_name == 'command_undefined'
        - name: Check test_command_undefined backup command section
          ansible.builtin.command:
            cmd: grep "## バックアップ処理" "{{ backup_script_dir }}/test_command_undefined"
          failed_when: grep_result.rc > 1
          changed_when: false
          register: grep_result
        - name: Assert backup command section
          ansible.builtin.assert:
            that: grep_result.rc == 1
    - name: Test command only
      become: true
      become_user: command_only
      block:
        - name: Check backup script
          ansible.builtin.stat:
            path: "{{ backup_script_dir }}/test_command_only"
          register: backup_script_result
        - name: Assert backup script
          ansible.builtin.assert:
            that:
              - backup_script_result.stat.exists
              - backup_script_result.stat.isreg
              - backup_script_result.stat.pw_name == 'command_only'
              - backup_script_result.stat.executable
        - name: Check backup data directory
          ansible.builtin.stat:
            path: "{{ backup_data_dir }}/test_command_only"
          register: backup_data_dir_result
        - name: Assert backup dir
          ansible.builtin.assert:
            that:
              - backup_data_dir_result.stat.exists
              - backup_data_dir_result.stat.isdir
              - backup_data_dir_result.stat.writeable
              - backup_data_dir_result.stat.pw_name == 'command_only'
        - name: Check test_command_only backup command section
          ansible.builtin.command:
            cmd: grep "echo test_command_only >" "{{ backup_script_dir }}/test_command_only"
          failed_when: grep_result.rc > 1
          changed_when: false
          register: grep_result
        - name: Debug
          ansible.builtin.debug:
            var: grep_result
        - name: Assert test_command_only backup command
          ansible.builtin.assert:
            that: grep_result.rc == 0
    # - name: Test restic default
    #   block:
    # - name: Test restic forget keep param
    #   block:
    # - name: Test restic and rclone
    #   block:
