# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    ## テストの前処理
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
      become: true
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    - name: Assert packages
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['rclone'] is defined
          - ansible_facts.packages['restic'] is defined
    - name: Test command undefined
      become: true
      become_user: command_undefined
      block:
        - name: Check backup script
          ansible.builtin.stat:
            path: "{{ backup_script_dir }}/test_command_undefined"
          register: backup_script_result
        - name: Assert backup script
          ansible.builtin.assert:
            that:
              - backup_script_result.stat.exists
              - backup_script_result.stat.isreg
              - backup_script_result.stat.pw_name == 'command_undefined'
              - backup_script_result.stat.executable
        - name: Check backup data directory
          ansible.builtin.stat:
            path: "{{ backup_data_dir }}/test_command_undefined"
          register: backup_data_dir_result
        - name: Assert backup dir
          ansible.builtin.assert:
            that:
              - backup_data_dir_result.stat.exists
              - backup_data_dir_result.stat.isdir
              - backup_data_dir_result.stat.writeable
              - backup_data_dir_result.stat.pw_name == 'command_undefined'
        - name: Check
          ansible.builtin.lineinfile:
            path: "{{ backup_script_dir }}/test_command_undefined"
            line: "## バックアップ処理"
          register: lineinfile_result
          check_mode: true
        - name: Assert backup dir
          ansible.builtin.assert:
            that: lineinfile_result is changed
    # - name: Test command only
    #   block:
    # - name: Test restic default
    #   block:
    # - name: Test restic forget keep param
    #   block:
    # - name: Test restic and rclone
    #   block:
