---
## --------
## rcloneを利用するテストのみ設定を上書き
## --------
backup_settings:
  ## バックアップ処理の指定：無し、バックアップデータの世代管理：有り
  ## 外部ストレージ(rclone経由)を利用した世代管理の指定
  test_restic_only_with_rclone:
    restic:
      repo: cloudflare_r2:test/bookworm/restic_only_with_rclone
  ## バックアップ処理の指定：有り、バックアップデータの世代管理：有り
  ## 外部ストレージ(rclone経由)を利用した世代管理の指定
  test_restic_and_rclone:
    restic:
      repo: cloudflare_r2:test/bookworm/test_restic_and_rclone
  redmine:
    restic:
      repo: cloudflare_r2:test/bookworm/redmine
