# code: language=ansible
---
- name: Test backup script:test_restic_no_forget
  block:
    - name: Check backup script:test_restic_no_forget
      ansible.builtin.stat:
        path: "{{ backup_script_dir }}/test_restic_no_forget"
      register: backup_script_result
    - name: Assert backup script:test_restic_no_forget
      ansible.builtin.assert:
        that:
          - backup_script_result.stat.exists
          - backup_script_result.stat.isreg
          - backup_script_result.stat.pw_name == 'restic_no_forget'
          - backup_script_result.stat.gr_name == 'restic_no_forget'
          - backup_script_result.stat.executable
        fail_msg: "Backup script for test_restic_no_forget is not properly configured"
        success_msg: "Backup script for test_restic_no_forget is properly configured"
- name: Test backup data directory:test_restic_no_forget
  block:
    - name: Check backup data directory:test_restic_no_forget
      ansible.builtin.stat:
        path: "{{ backup_data_dir }}/test_restic_no_forget"
      register: backup_data_dir_result
    - name: Assert backup data directory:test_restic_no_forget
      ansible.builtin.assert:
        that:
          - backup_data_dir_result.stat.exists
          - backup_data_dir_result.stat.isdir
          - backup_data_dir_result.stat.writeable
          - backup_data_dir_result.stat.pw_name == 'restic_no_forget'
          - backup_data_dir_result.stat.gr_name == 'restic_no_forget'
        fail_msg: "Backup data directory for test_restic_no_forget is not properly configured"
        success_msg: "Backup data directory for test_restic_no_forget is properly configured"
- name: Test repository password file:test_restic_no_forget
  block:
    - name: Check repository password file:test_restic_no_forget
      ansible.builtin.stat:
        path: "{{ backup_repo_password_dir }}/test_restic_no_forget"
      register: repo_password_file_result
    - name: Assert repository password file:test_restic_no_forget
      ansible.builtin.assert:
        that:
          - repo_password_file_result.stat.exists
          - repo_password_file_result.stat.isreg
          - repo_password_file_result.stat.writeable
          - repo_password_file_result.stat.pw_name == 'restic_no_forget'
          - repo_password_file_result.stat.gr_name == 'restic_no_forget'
          - repo_password_file_result.stat.mode == '0640'
        fail_msg: "Repository password file for test_restic_no_forget is not properly configured"
        success_msg: "Repository password file for test_restic_no_forget is properly configured"
- name: Test repository directory:test_restic_no_forget
  block:
    - name: Check repository directory:test_restic_no_forget
      ansible.builtin.stat:
        path: "{{ backup_repo_dir }}/test_restic_no_forget"
      register: backup_repo_dir_result
    - name: Assert repository directory:test_restic_no_forget
      ansible.builtin.assert:
        that:
          - backup_repo_dir_result.stat.exists
          - backup_repo_dir_result.stat.isdir
          - backup_repo_dir_result.stat.writeable
          - backup_repo_dir_result.stat.pw_name == 'restic_no_forget'
          - backup_repo_dir_result.stat.gr_name == 'restic_no_forget'
          - backup_repo_dir_result.stat.mode == '0750'
        fail_msg: "Repository directory for test_restic_no_forget is not properly configured"
        success_msg: "Repository directory for test_restic_no_forget is properly configured"
- name: Test cron setting:test_restic_no_forget
  block:
    - name: Check cron setting:test_restic_no_forget
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          crontab -l | grep "#Ansible: role:backup/setting:test_restic_no_forget"
        executable: /bin/bash
      failed_when: cron_setting_result.rc > 1
      changed_when: false
      register: cron_setting_result
    - name: Assert cron setting:test_restic_no_forget
      ansible.builtin.assert:
        that: cron_setting_result.rc == 0
        fail_msg: "Cron setting for test_restic_no_forget is not configured"
        success_msg: "Cron setting for test_restic_no_forget is properly configured"
- name: Test backup script detail:test_restic_no_forget
  block:
    - name: Check backup command section:test_restic_no_forget
      ansible.builtin.command:
        cmd: grep "rclone test makefile 1234" "{{ backup_script_dir }}/test_restic_no_forget"
      failed_when: backup_command_result.rc > 1
      changed_when: false
      register: backup_command_result
    - name: Assert backup command:test_restic_no_forget
      ansible.builtin.assert:
        that: backup_command_result.rc == 0
        fail_msg: "Backup command validation failed"
        success_msg: "Backup command is properly configured"
    - name: Check restic forget command:test_restic_no_forget
      ansible.builtin.command:
        cmd: grep "restic forget" "{{ backup_script_dir }}/test_restic_no_forget"
      failed_when: restic_forget_command_result.rc > 1
      changed_when: false
      register: restic_forget_command_result
    - name: Assert restic forget command:test_restic_no_forget
      ansible.builtin.assert:
        that: restic_forget_command_result.rc == 1
        fail_msg: "Restic forget command should not exist"
        success_msg: "Restic forget command correctly not found"
    - name: Execute backup script:test_restic_no_forget
      ansible.builtin.command:
        cmd: "{{ backup_script_dir }}/test_restic_no_forget"
      changed_when: false
      register: exec_backup_script_result
    - name: Assert execute backup script result:test_restic_no_forget
      ansible.builtin.assert:
        that: exec_backup_script_result.rc == 0
        fail_msg: "Backup script execution failed"
        success_msg: "Backup script executed successfully"
    - name: Check backup script generated file:test_restic_no_forget
      ansible.builtin.stat:
        path: "{{ backup_data_dir }}/test_restic_no_forget/test.txt"
      register: backup_script_generated_file_result
    - name: Assert backup script generated file:test_restic_no_forget
      ansible.builtin.assert:
        that:
          - backup_script_generated_file_result.stat.exists
          - backup_script_generated_file_result.stat.isreg
          - backup_script_generated_file_result.stat.pw_name == 'restic_no_forget'
        fail_msg: "Generated file not properly created"
        success_msg: "Generated file properly created"
