# code: language=ansible
---
- name: Test backup script:test_shared_data_and_repo
  block:
    - name: Check backup script:test_shared_data_and_repo
      ansible.builtin.stat:
        path: "{{ backup_script_dir }}/test_shared_data_and_repo"
      register: backup_script_result
    - name: Assert backup script:test_shared_data_and_repo
      ansible.builtin.assert:
        that:
          - backup_script_result.stat.exists
          - backup_script_result.stat.isreg
          - backup_script_result.stat.pw_name == 'shared_data_and_repo_main'
          - backup_script_result.stat.gr_name == 'shared_data_and_repo'
          - backup_script_result.stat.executable
          - backup_script_result.stat.mode == '0700'
        fail_msg: "Backup script for test_shared_data_and_repo is not properly configured"
        success_msg: "Backup script for test_shared_data_and_repo is properly configured"
- name: Test backup data directory:test_shared_data_and_repo
  block:
    - name: Check backup data directory:test_shared_data_and_repo
      ansible.builtin.stat:
        path: "{{ backup_data_dir }}/test_shared_data_and_repo"
      register: backup_data_dir_result
    - name: Assert backup data directory:test_shared_data_and_repo
      ansible.builtin.assert:
        that:
          - backup_data_dir_result.stat.exists
          - backup_data_dir_result.stat.isdir
          - backup_data_dir_result.stat.writeable
          - backup_data_dir_result.stat.pw_name == 'shared_data_and_repo_main'
          - backup_data_dir_result.stat.gr_name == 'shared_data_and_repo'
          - backup_data_dir_result.stat.mode == '0750'
        fail_msg: "Backup data directory for test_shared_data_and_repo is not properly configured"
        success_msg: "Backup data directory for test_shared_data_and_repo is properly configured"
- name: Test repository password file:test_shared_data_and_repo
  block:
    - name: Check repository password file:test_shared_data_and_repo
      ansible.builtin.stat:
        path: "{{ backup_repo_password_dir }}/test_shared_data_and_repo"
      register: repo_password_file_result
    - name: Assert repository password file:test_shared_data_and_repo
      ansible.builtin.assert:
        that:
          - repo_password_file_result.stat.exists
          - repo_password_file_result.stat.isreg
          - repo_password_file_result.stat.writeable
          - repo_password_file_result.stat.pw_name == 'shared_data_and_repo_main'
          - repo_password_file_result.stat.gr_name == 'shared_data_and_repo'
          - repo_password_file_result.stat.mode == '0640'
        fail_msg: "Repository password file for test_shared_data_and_repo is not properly configured"
        success_msg: "Repository password file for test_shared_data_and_repo is properly configured"
- name: Test repository directory:test_shared_data_and_repo
  block:
    - name: Check repository directory:test_shared_data_and_repo
      ansible.builtin.stat:
        path: "{{ backup_repo_dir }}/test_shared_data_and_repo"
      register: backup_repo_dir_result
    - name: Assert backup data directory:test_shared_data_and_repo
      ansible.builtin.assert:
        that:
          - backup_repo_dir_result.stat.exists
          - backup_repo_dir_result.stat.isdir
          - backup_repo_dir_result.stat.writeable
          - backup_repo_dir_result.stat.pw_name == 'shared_data_and_repo_main'
          - backup_repo_dir_result.stat.gr_name == 'shared_data_and_repo'
          - backup_repo_dir_result.stat.mode == '0750'
        fail_msg: "Repository directory for test_shared_data_and_repo is not properly configured"
        success_msg: "Repository directory for test_shared_data_and_repo is properly configured"
